# Generated by Django 4.2.3 on 2023-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0002_alter_tag_name_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="todo_list.tag"),
        ),
    ]
